exclude: ^(.*outputs|.*assets|\.venv)
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-merge-conflict

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt
        args: [--indent, "2", --write]
        stages: [pre-commit]

  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        args: [--config, "./.checkmake.ini"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: dir_checker
        name: validate directories
        language: python
        entry: env PYTHONPATH=. uv run --active --no-sync scripts/dir_checker/main.py
        pass_filenames: false

  - repo: local
    hooks:
      - id: python_checker
        name: validate python files
        language: python
        entry: env PYTHONPATH=. uv run --active --no-sync scripts/python_checker/main.py

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests==2.32.0.20250328]

  - repo: https://github.com/pycqa/pylint
    rev: v3.3.6
    hooks:
      - id: pylint
